on:
  push:
    tags:    
      - "*"

jobs:
  build-proton-ge:
    runs-on: macos-10.15
    env:
      # avoids hanging the system with vagrant checking for updates
      VAGRANT_CHECKPOINT_DISABLE: yes
      # Extract the tag name without refs/tags
      RELEASE_VERSION: ${GITHUB_REF#refs/*/}
      # Dedicated file for github actions compatible 
      # with the gh-actions environment
      VAGRANT_VAGRANTFILE: Vagrantfile.github
    steps:
      - name: Display version
        run: echo ${{ env.RELEASE_VERSION }}

      - name: Install dependencies
        run: brew install coreutils
      # would be a shame to wait 2 hours for the
      # compilation to finish only to realise sha512sum is not
      # available
      - name: Test sha512sum availability
        run: echo "hello" | sha512sum

      - uses: actions/checkout@master
        with:
          submodules: false

      - name: Update submodules
        run: |
          set -o xtrace
          git submodule update --init --recursive
          
      - name: Show Vagrant version
        run: vagrant --version
      
        # without this the share directory mounting fails
        # probably because the guest additions are old
      - name: Setup vbox additions
        run: vagrant plugin install vagrant-vbguest

      - name: apply patches
        run: ./patches/protonprep.sh

      - name: Run vagrant up
        run: vagrant up --no-tty
      - name: Run vagrant up
        run: vagrant up --no-tty

      # Build name following convention: Proton-<tag>
      - name: Build proton
        run: build_name=Proton-${{ env.RELEASE_VERSION }} make redist

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_PAT }}
          file: vagrant_share/*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: false